# Generated by Django 2.2.2 on 2019-08-20 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('p_falladas', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('p_acertadas', models.IntegerField()),
                ('fallos', models.IntegerField()),
                ('nota', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Examenes',
            },
        ),
    ]
