# Generated by Django 2.2.2 on 2019-08-18 02:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', tinymce.models.HTMLField(verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
                'ordering': ['capitulo'],
            },
        ),
        migrations.CreateModel(
            name='Oposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oposicion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Oposición',
                'verbose_name_plural': 'Oposiciones',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('oposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.Oposicion')),
            ],
            options={
                'verbose_name_plural': 'Temas',
                'ordering': ['tema'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(max_length=255)),
                ('res_a', models.TextField(max_length=255)),
                ('res_b', models.TextField(max_length=255)),
                ('res_c', models.TextField(max_length=255)),
                ('correcta', models.CharField(max_length=1)),
                ('capitulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oposicion.Capitulo')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oposicion.Tema')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposicion.Tema'),
        ),
    ]
