# Generated by Django 2.2.2 on 2019-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oposicion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='conocimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='conocimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
